config/routes.rb
Rails.application.routes.draw do
  get 'user/show'

  devise_for :users, :controllers => { registrations: 'registrations'}
  get 'home/index'

  resources :homeworks

  authenticated :user do
    root 'home#index'
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

end

app/models/homework.rb
class Homework < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :first_name, :last_name
  devise :database_authenticatable, :registerable,
          :trackable, :validatable

  require 'carrierwave/orm/activerecord'

  mount_uploader :avatar, AvatarUploader

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email,
     :password, :password_confirmation) }
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name,
     :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache) }
 end

#  validates_presence_of   :avatar
#  validates_integrity_of  :avatar
#  validates_processing_of :avatar

  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up) do |user_params|
     user_params.permit({ roles: [:professor] }, :first_name, :last_name, :email, :password, :password_confirmation)
   end
 end

 def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u|
      u.permit(:first_name, :last_name, :avatar, :avatar_cache, :email, :bio, :password, :password_confirmation, :current_password)
    }
  end

 def authenticate_user!(options={})
   if user_signed_in?
     super(options)
   else
     redirect_to login_path, :notice => 'if you want to add a notice'
     ## if you want render 404 page
     ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
   end
 end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  before_filter :authenticate_user!
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]

  # GET /homeworks
  # GET /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = Homework.new(homework_params)

    respond_to do |format|
      if @homework.save
        redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
      else
        render "new"
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_params
      params.require(:homework).permit(:name, :attachment, :info)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :professor)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    if current_user
      @user = current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
  current_page?(link_path) ? "active" : ""
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/homeworks/_form.html.erb
<%= form_for(@homework) do |f| %>
  <% if @homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
      <% @homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.text_field :attachment %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homeworks/edit.html.erb
<h1>Editing Homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Homeworks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Attachment</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.name %></td>
        <td><%= homework.attachment %></td>
        <td><%= homework.info %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

app/views/homeworks/new.html.erb
<h1>New Homework</h1>

<%= render 'form' %>

<%= link_to 'Back', homeworks_path %>

app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @homework.name %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= @homework.attachment %>
</p>

<p>
  <strong>Info:</strong>
  <%= @homework.info %>
</p>

<%= link_to 'Edit', edit_homework_path(@homework) %> |
<%= link_to 'Back', homeworks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>Slife</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
   </head>
   <% if !user_signed_in? %>
   <body id="sign-bg">
      <% else %>
      <body>
         <header id="header">
            <nav class="navbar navbar-default">
               <div class="container-fluid">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div id="header-mobile-height" class="navbar-header">
                     <button id="collapsed-button" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation-bar" aria-expanded="false">
                     <span class="sr-only">Toggle navigation</span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     </button>
                     <a id="logo" class="navbar-brand" href="#">Slife</a>
                  </div>
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse" id="navigation-bar">
                     <ul class="nav navbar-nav">
                        <li class="<%= active_class(root_path) %>"><%= link_to "Home", root_path %><span class="sr-only">(current)</span></li>
                        <li class="<%= active_class(user_show_path) %>"><%= link_to "Profile", user_show_path %></li>
                     </ul>
                     <span id="user-credentials">
                     Welcome,
                     <% if current_user.professor? %>
                     Professor <%= current_user.full_name %>!
                     <% else %>
                     <%= current_user.full_name %>!
                     <% end %>
                     <%= link_to(raw("<span class='glyphicon glyphicon-off'>"), destroy_user_session_path, :method => :delete, :id => "logout")  %>
                     </span>
                  </div>
               </div>
            </nav>
         </header>
         <% end %>
         <main class="container">
            <%= yield %>
         </main>
   </body>
</html>

app/views/user/show.html.erb
<div class="page-heading">
  <h1>Profile</h1>
</div>
<div id="profile-panel-size" class="panel panel-default">
  <div class="panel-body">
      <% if current_user.avatar? %>
      <%= image_tag(current_user.avatar.url, id: "user-avatar",class: "img-thumbnail img-responsive") %>
      <% else %>
      <%= image_tag('avatar-placeholder.png', id: "user-avatar",class: "img-thumbnail img-responsive") %>
      <% end %>
      <div id="user-name"><%= current_user.full_name %></div>
      <div id="user-primary-container">
        <span id="user-email"><%= current_user.email %></span>
      </div>
      <div id="user-secondary-container">
        <h2 class="user-label">Bio</h2>
        <% if current_user.bio? %>
        <p class="user-info">
         <%= current_user.bio %>
        </p>
         <% else %>
         <span id="no-bio">Edit your profile to change this section!</span>
         <% end %>
      </div>
      <div id="user-tertiary-container" class="container">
        <div class="pos-btn row">
          <div class="col-md-6">
            <%= link_to "Edit your Profile", edit_user_registration_path, class: "btn btn-default profile-btn-edit" %>
          </div>
          <div class="col-md-6">
          <%= link_to "Delete Account" , user_registration_path, class: "btn btn-default profile-btn-destroy",method: :delete, confirm: 'Are You Sure?' %>
          </div>
        </div>
      </div>
  </div>
</div>